### ISSUE TITLE
CEQR Air quality

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/ceqr-app-data-archive#22]
| file_name                                    | description                                      |
| -------------------------------------------- | ------------------------------------------------ |
| dot_traffic_cameras.zip                      | DOT traffic cameras                              |
| nysdot_functional_class.zip                  | NYS DOT Functional Class                         |
| nysdot_aadt.zip                              | NYS Traffic Volume Data                          |
| nysdot_traffic_counts.zip (2015, 2016, 2017) | General Highway Data                             |
| nysdec_air_monitoring_stations.zip           | Air monitoring stations                          |
| facilities_garages.zip                       | Garages                                          |
| tunnel_ventilation_tower_map.geojson         | Ventilation Outlets                              |
| area_of_concern.geojson                      | Areas of Concern                                 |
| atypical_roadways.geojson                    | Atypical Roadway                                 |
| dep_cats_permits.zip                         | Manufacturing or processing facilities, boilers  |
| nysdec_facility_permits.zip                  | Title V State Permits and Facility State Permits |

**Comment by AmandaDoyle** [comment]
Package up data in file geodatabase and make available in ArcMap
Layers that should be in ArcMap:
Checked once if they're there in the gbd, checked a second time if they've been okayed by Amanda, checked a third time if they've been reviewed by Lynn and ready for EARD

- [x] DOT traffic cameras
- [x] DOT traffic cameras (add URL field to dataset)
- [ ] DOT traffic cameras
--
- [x] NYS DOT Functional Class
- [x] NYS DOT Functional Class
- [ ] NYS DOT Functional Class
--
- [x] NYS Traffic Volume Data
- [x] NYS Traffic Volume Data (AADT layer)
- [ ] NYS Traffic Volume Data
--
- [x] General Highway Data
- [x] General Highway Data - three tables of volume by year.  Need to work with Cary on how to make these spatial and useful
- [ ] General Highway Data
--
- [x] Air monitoring stations 
- [x] Air monitoring stations (need to make spatial dataset)
- [ ] Air monitoring stations 
--
- [x] Garages
- [x] Garages
- [ ] Garages 
--
- [x] Ventilation Outlets
- [x] Ventilation Outlets
- [ ] Ventilation Outlets
--
- [x] Areas of Concern
- [x] Areas of Concern
- [ ] Areas of Concern
--
- [x] Atypical Roadway
- [x] Atypical Roadway
- [ ] Atypical Roadway
--
- [x] Manufacturing or processing facilities, boilers
- [x] Manufacturing or processing facilities, boilers (DEP Cats - (need to make spatial dataset))
- [ ] Manufacturing or processing facilities, boilers
--
- [x] Title V State Permits
- [x] Title V State Permits (need to make spatial dataset)
- [ ] Title V State Permits
--
- [x] Facility State Permits
- [x] Facility State Permits (need to make spatial dataset)
- [ ] Facility State Permits
